theme: just-the-docs

title: Kernel Memory
description: >-
  Index and query any data using LLM and natural language, tracking sources and
  showing citations. Kernel Memory (KM) is a multi-modal AI Service specialized
  in the efficient indexing of datasets through custom continuous data hybrid
  pipelines, with support for Retrieval Augmented Generation (RAG), synthetic
  memory, prompt engineering, and custom semantic memory processing.
baseurl: "/kernel-memory"
url: ""

plugins:
  - jekyll-feed

favicon_ico: "/favicon.png"
search_enabled: true
enable_copy_code_button: true
heading_anchors: true
color_scheme: custom

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

nav_external_links:
- title: KM on GitHub
  url: https://github.com/microsoft/kernel-memory
- title: KM on Discord
  url: https://aka.ms/KMDiscord

aux_links:
  "GitHub":
    - "https://github.com/microsoft/kernel-memory"
  "Discord":
    - "https://aka.ms/KMDiscord"

back_to_top: false
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Edit this page"
gh_edit_repository: "https://github.com/microsoft/kernel-memory"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"
