# Build Docker image and push it to docker hub

name: Dockerize arm64

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Enter KM version (for docker tag)"
        required: true
        default: "0.000.000000.0"

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04-arm
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/service
          tags: |
            type=raw,priority=800,value=${{ github.event.inputs.docker_tag }}-arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          # See https://github.com/dotnet/dotnet-docker/blob/main/README.sdk.md#full-tag-listing
          build-args: |
            BUILD_IMAGE_TAG=9.0-noble-arm64v8
            RUN_IMAGE_TAG=9.0-alpine-arm64v8
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
