name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'feature*'
      - 'dev'
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - 'appsettings.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dotnet-build:
    name: Build
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - { dotnet: "8.0.x", os: "ubuntu-latest", configuration: Debug }
          - { dotnet: "8.0.x", os: "ubuntu-latest", configuration: Release }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet}}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Display .NET version
        run: dotnet --version

      - name: Build solution
        run: dotnet build KernelMemory.sln -c ${{ matrix.configuration }} /warnaserror
